apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  template:
    spec:
      containers:
      - name: init
        image: content-init
        env:
          - name: MONGODB_CONNECTION
            value: mongodb://mongodb:27017/contentdb
      restartPolicy: Never
  backoffLimit: 4