apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 27017
    targetPort: 27017
  selector:
    name: mongo-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  mongo-db-deploy
  labels:
    name:  mongo-db
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  mongo-db
    spec:
      containers:
      - image:  mongo
        name:  mongo-db-cntnr
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  27017
          name:  mongo-db
        volumeMounts:
        - mountPath: /data/db
          name: azuredisk-db
        - mountPath: /data/configdb
          name: azuredisk-configdb
        imagePullPolicy: Always
      volumes:
        - name: azuredisk-db
          azureDisk:
            kind: Managed
            diskName: mongodb-datadisk
            diskURI: [INSERT YOUR DISK ID , e.g /subscriptions/ebb856bd-cdcb-4e79-92bd-02911c47395f/resourceGroups/MC_fabmedical-aks-rg_fabmed_eastus/providers/Microsoft.Compute/disks/mongodb-datadisk]
        - name: azuredisk-configdb
          azureDisk:
            kind: Managed
            diskName: mongodb-configdisk
            diskURI:  [INSERT YOUR DISK ID , /subscriptions/ebb856bd-cdcb-4e79-92bd-02911c47395f/resourceGroups/MC_fabmedical-aks-rg_fabmed_eastus/providers/Microsoft.Compute/disks/mongodb-configdisk]
      restartPolicy: Always