apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: YOUR_ACR_NAME.azurecr.io/content-web
        name: web
        env:
        - name: CONTENT_API_URL
          value: http://api:3001
        tty: true
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: web
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: YOUR_AKS_CLUSTER_NAME.YOUR_AKS_DNS_ID.YOUR_AKS_REGION.aksapp.io
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80
        path: /